// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WahaWikiAPI.Database;

#nullable disable

namespace WahaWikiAPI.Migrations
{
    [DbContext(typeof(WahaDbContext))]
    partial class WahaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WahaWikiAPI.Entities.Abilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitAbilitiesRelationships", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("AbilitiesId")
                        .HasColumnType("int");

                    b.HasKey("UnitId", "AbilitiesId");

                    b.HasIndex("AbilitiesId");

                    b.ToTable("UnitAbilitiesRelationships");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Attacks")
                        .HasColumnType("int");

                    b.Property<int>("BS")
                        .HasColumnType("int");

                    b.Property<int>("Leadership")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumber")
                        .HasColumnType("int");

                    b.Property<int>("MinNumber")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Move")
                        .HasColumnType("int");

                    b.Property<int>("PointPrice")
                        .HasColumnType("int");

                    b.Property<int>("SavingThrows")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Toughness")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("WS")
                        .HasColumnType("int");

                    b.Property<int>("Wounds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("StatLines");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitTypes");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitWeaponRelationships", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("UnitId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("UnitWeaponRelationships");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"), 1L, 1);

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfShot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("int");

                    b.HasKey("WeaponId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.WeaponAbilities", b =>
                {
                    b.Property<int>("WeaponAbilitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponAbilitiesId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponAbilitiesId");

                    b.ToTable("WeaponAbilities");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.WeaponAbilitiesRelationships", b =>
                {
                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponAbilitiesId")
                        .HasColumnType("int");

                    b.HasKey("WeaponId", "WeaponAbilitiesId");

                    b.HasIndex("WeaponAbilitiesId");

                    b.ToTable("WeaponAbilitiesRelationships");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeRuleText")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeaponTypes");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.Unit", b =>
                {
                    b.HasOne("WahaWikiAPI.Entities.UnitType", "UnitType")
                        .WithMany("UnitList")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitAbilitiesRelationships", b =>
                {
                    b.HasOne("WahaWikiAPI.Entities.Abilities", "Abilities")
                        .WithMany("UnitAbilitiesRelationships")
                        .HasForeignKey("AbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WahaWikiAPI.Entities.Unit", "Unit")
                        .WithMany("UnitAbilitiesRelationships")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abilities");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitStat", b =>
                {
                    b.HasOne("WahaWikiAPI.Entities.Unit", "Unit")
                        .WithMany("UnitStatList")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitWeaponRelationships", b =>
                {
                    b.HasOne("WahaWikiAPI.Entities.Unit", "Unit")
                        .WithMany("UnitWeaponRelationships")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WahaWikiAPI.Entities.Weapon", "Weapon")
                        .WithMany("UnitWeaponRelationships")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.Weapon", b =>
                {
                    b.HasOne("WahaWikiAPI.Entities.WeaponType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.WeaponAbilitiesRelationships", b =>
                {
                    b.HasOne("WahaWikiAPI.Entities.WeaponAbilities", "WeaponAbilities")
                        .WithMany("WeaponAbilitiesRelationships")
                        .HasForeignKey("WeaponAbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WahaWikiAPI.Entities.Weapon", "Weapon")
                        .WithMany("WeaponAbilitiesRelationships")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");

                    b.Navigation("WeaponAbilities");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.Abilities", b =>
                {
                    b.Navigation("UnitAbilitiesRelationships");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.Unit", b =>
                {
                    b.Navigation("UnitAbilitiesRelationships");

                    b.Navigation("UnitStatList");

                    b.Navigation("UnitWeaponRelationships");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.UnitType", b =>
                {
                    b.Navigation("UnitList");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.Weapon", b =>
                {
                    b.Navigation("UnitWeaponRelationships");

                    b.Navigation("WeaponAbilitiesRelationships");
                });

            modelBuilder.Entity("WahaWikiAPI.Entities.WeaponAbilities", b =>
                {
                    b.Navigation("WeaponAbilitiesRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
